// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Home_index from "./routes/Home/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_relativePath_ from "./routes/blog/[relativePath].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $HeaderNav from "./islands/HeaderNav.tsx";
import * as $HeaderSearch from "./islands/HeaderSearch.tsx";
import * as $MarkdownPageRenderer from "./islands/MarkdownPageRenderer.tsx";
import * as $Pagination from "./islands/Pagination.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Home/index.tsx": $Home_index,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/[relativePath].tsx": $blog_relativePath_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/HeaderNav.tsx": $HeaderNav,
    "./islands/HeaderSearch.tsx": $HeaderSearch,
    "./islands/MarkdownPageRenderer.tsx": $MarkdownPageRenderer,
    "./islands/Pagination.tsx": $Pagination,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
